import { db } from "@/lib/db";
import type { SessionUser } from "@/lib/auth";
import { assertCompanyPermission, canCompany, PermissionError } from "@/lib/permissions";
import type { DocDept } from "@/generated/prisma/enums";
import { Prisma } from "@/generated/prisma/client";

export async function listCompanyTemplates(user: SessionUser) { if (!(await canCompany(user, "engineering_standards", "read")) && !(await canCompany(user, "legal_escalation", "read"))) throw new PermissionError("Company role cannot read controlled templates"); return db.documentTemplate.findMany({ orderBy: [{ issuingDepartment: "asc" }, { docNo: "asc" }, { revisionNo: "desc" }] }); }
export async function createCompanyTemplate(user: SessionUser, input: { docNo: string; title: string; issuingDepartment: DocDept; revisionNo: number; effectiveDate: string; formSchema?: unknown }) { const approvalType = input.issuingDepartment === "CONTRACTS" ? "CONTRACT_TEMPLATE" : "DESIGN_STANDARD"; await assertCompanyPermission(user, approvalType === "CONTRACT_TEMPLATE" ? "legal_escalation" : "engineering_standards", "create"); const template = await db.documentTemplate.create({ data: { docNo: input.docNo, title: input.title, issuingDepartment: input.issuingDepartment, revisionNo: input.revisionNo, effectiveDate: new Date(input.effectiveDate), formSchema: (input.formSchema ?? {}) as Prisma.InputJsonValue } }); await db.companyApproval.create({ data: { organizationId: user.organizationId, type: approvalType, entityType: "DocumentTemplate", entityId: template.id, requestedById: user.id } }); return template; }
export async function listCompanyFleet(user: SessionUser) { await assertCompanyPermission(user, "equipment_capital", "read"); return db.equipment.findMany({ where: { organizationId: user.organizationId }, include: { usageLogs: { orderBy: { date: "desc" }, take: 20 }, allocations: { where: { releasedAt: null }, include: { project: { select: { code: true, name: true } }, allocatedBy: { select: { fullName: true } } }, orderBy: { allocatedFrom: "desc" } } }, orderBy: { equipmentType: "asc" } }); }
export async function requestEquipmentCapital(user: SessionUser, input: { action: "ACQUIRE" | "DISPOSE"; equipmentId?: string; equipmentType: string; plateNo?: string; serialNo?: string; amount: number; comment?: string }) { await assertCompanyPermission(user, "equipment_capital", "create"); const entityId = input.equipmentId ?? `NEW:${input.equipmentType}:${Date.now()}`; return db.companyApproval.create({ data: { organizationId: user.organizationId, type: "EQUIPMENT_CAPITAL", entityType: "Equipment", entityId, requestedById: user.id, amount: input.amount, comment: input.comment, thresholdSnapshot: input as any } }); }
